services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sportify-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - sqlserver_data:/var/opt/mssql

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    container_name: sportify-db-init
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      /bin/bash -c "
      echo 'Initializing Database sportify...' &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${DB_PASSWORD} -Q 'IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N\"sportify\") CREATE DATABASE [sportify];'
      "

volumes:
  sqlserver_data:
